<style type="text/css">
#cloud_control{
	position:fixed;
	right:0px;
	bottom:200px;
	color:white;
	background:white;
	border:1px white solid;
	padding:5px;
	-moz-border-radius:3px;
	border-radius:3px;
	background: rgb(246,248,249); /* Old browsers */
	background: -moz-linear-gradient(top, rgba(246,248,249,1) 0%, rgba(229,235,238,1) 50%, rgba(215,222,227,1) 61%, rgba(245,247,249,1) 100%); /* FF3.6+ */
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(246,248,249,1)), color-stop(50%,rgba(229,235,238,1)), color-stop(61%,rgba(215,222,227,1)), color-stop(100%,rgba(245,247,249,1))); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(top, rgba(246,248,249,1) 0%,rgba(229,235,238,1) 50%,rgba(215,222,227,1) 61%,rgba(245,247,249,1) 100%); /* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(top, rgba(246,248,249,1) 0%,rgba(229,235,238,1) 50%,rgba(215,222,227,1) 61%,rgba(245,247,249,1) 100%); /* Opera 11.10+ */
	background: -ms-linear-gradient(top, rgba(246,248,249,1) 0%,rgba(229,235,238,1) 50%,rgba(215,222,227,1) 61%,rgba(245,247,249,1) 100%); /* IE10+ */
	background: linear-gradient(to bottom, rgba(246,248,249,1) 0%,rgba(229,235,238,1) 50%,rgba(215,222,227,1) 61%,rgba(245,247,249,1) 100%); /* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f6f8f9', endColorstr='#f5f7f9',GradientType=0 ); /* IE6-9 */

	-webkit-box-shadow: 0px 0px 20px rgba(100,100,100,.8);
   	-moz-box-shadow: 0px 0px 20px rgba(100,100,100,.8);
   	box-shadow: 0px 0px 20px rgba(100,100,100,.8);

	line-height:0.5em;

}
#cloud_control a{
	line-height:1.5em;
	font-size:1.3em;
	-webkit-box-shadow: 0px 0px 20px rgba(100,100,100,.8);
   	-moz-box-shadow: 0px 0px 20px rgba(100,100,100,.8);
   	box-shadow: 0px 0px 20px rgba(100,100,100,.8);
	cursor:pointer;
}
</style>
<div id="cloud_control">
<a class="btn btn-info">My music</a><br><br>
<a class="btn btn-info">All music&nbsp;</a><br><br>
<a class="btn btn-info">&nbsp;&nbsp; Search&nbsp;&nbsp;</a>
</div>
