<div id="keys" >
<a class="key_help">A</a>
<div class="key" id="65_key"></div>

<div class="key_small" >
<a class="key_help_small">Q</a>
</div>

<a class="key_help">S</a>
<div class="key" id="83_key" ></div>

<div class="key_small" >
<a class="key_help_small">W</a>
</div>

<a class="key_help">D</a>
<div class="key" id="68_key" ></div>

<div class="key_small" >
<a class="key_help_small">E</a>
</div>

<a class="key_help">F</a>
<div class="key" id="70_key" ></div>

<a class="key_help">G</a>
<div class="key" id="71_key" ></div>

<div class="key_small" >
<a class="key_help_small">R</a>
</div>

<a class="key_help">H</a>
<div class="key" id="72_key" ></div>

<div class="key_small" >
<a class="key_help_small">T</a>
</div>

<a class="key_help">J</a>
<div class="key" id="74_key" ></div>

<a class="key_help">K<br><br>Z</a>
<div class="key" id="75_key" ></div>

<div class="key_small" >
<a class="key_help_small">Y</a>
</div>

<a class="key_help">L<br><br>X</a>
<div class="key" id="76_key" ></div>

<!--this is just dummy -->
<div class="key_small" >
<a class="key_help_small">U</a>
</div>

<a class="key_help"> <br><br>C</a>
<div class="key" id="76_key" ></div>

<div class="key_small" >
<a class="key_help_small">I</a>
</div>

<a class="key_help"> <br><br>V</a>
<div class="key" id="76_key" ></div>

<a class="key_help"> <br><br>B</a>
<div class="key" id="76_key" ></div>

<div class="key_small" >
<a class="key_help_small">O</a>
</div>

<a class="key_help"> <br><br>N</a>
<div class="key" id="76_key" ></div>

<div class="key_small" >
<a class="key_help_small">P</a>
</div>

<a class="key_help"> <br><br>M</a>
<div class="key" id="76_key" ></div>


<!--
&nbsp;
&nbsp;
&nbsp;
<div class="key" id="165_key"></div>
<div class="key" id="183_key" ></div>
<div class="key" id="168_key" ></div>
<div class="key" id="170_key" ></div>
<div class="key" id="171_key" ></div>
<div class="key" id="172_key" ></div>
<div class="key" id="174_key" ></div>
<div class="key" id="175_key" ></div>
<div class="key" id="176_key" ></div>
-->

</div>
</div>
