<!-- This file is the sound library -->
<audio id='65' style='display:none;' src='sounds/SA1.ogg'>
<audio id='83' style='display:none;' src='sounds/RI1.ogg'>
<audio id='68' style='display:none;' src='sounds/GA1.ogg'>
<audio id='70' style='display:none;' src='sounds/MA1.ogg'>
<audio id='71' style='display:none;' src='sounds/PA1.ogg'>
<audio id='72' style='display:none;' src='sounds/DA1.ogg'>
<audio id='74' style='display:none;' src='sounds/NI1.ogg'>
<audio id='75' style='display:none;' src='sounds/SA2.ogg'>
<audio id='76' style='display:none;' src='sounds/RI2.ogg'>

<audio id='165' style='display:none;' src='sounds/SA2.ogg'>
<audio id='183' style='display:none;' src='sounds/RI2.ogg'>
<audio id='168' style='display:none;' src='sounds/GA2.ogg'>
<audio id='170' style='display:none;' src='sounds/MA2.ogg'>
<audio id='171' style='display:none;' src='sounds/PA2.ogg'>
<audio id='172' style='display:none;' src='sounds/DA2.ogg'>
<audio id='174' style='display:none;' src='sounds/NI2.ogg'>
<audio id='175' style='display:none;' src='sounds/SA1.ogg'>
<audio id='176' style='display:none;' src='sounds/RI1.ogg'>



<!-- TODO make it like this
<audio id='65' style='display:none;' src='sounds/hit.wav'
oncanplay="canplay()"
oncanplaythrough="another()"
onloadeddata="onloadeddata()">
-->
