<!-- This file is the sound library -->
<audio id='65' style='display:none;' src='sounds/SA1.ogg'>
<audio id='83' style='display:none;' src='sounds/RI1.ogg'>
<audio id='68' style='display:none;' src='sounds/GA1.ogg'>
<audio id='70' style='display:none;' src='sounds/MA1.ogg'>
<audio id='71' style='display:none;' src='sounds/PA1.ogg'>
<audio id='72' style='display:none;' src='sounds/DA1.ogg'>
<audio id='74' style='display:none;' src='sounds/NI1.ogg'>
<audio id='75' style='display:none;' src='sounds/SA2.ogg'>
<audio id='76' style='display:none;' src='sounds/RI2.ogg'>
<audio id='67' style='display:none;' src='sounds/GA2.ogg'>
<audio id='86' style='display:none;' src='sounds/MA2.ogg'>
<audio id='66' style='display:none;' src='sounds/PA2.ogg'>
<audio id='78' style='display:none;' src='sounds/DA2.ogg'>
<audio id='77' style='display:none;' src='sounds/NI2.ogg'>

<!--81 87 69 82 84 89 85 73 79 80 -->
<audio id='81' style='display:none;' src='sounds/RI12.ogg'>
<audio id='87' style='display:none;' src='sounds/GA12.ogg'>
<audio id='69' style='display:none;' src='sounds/MA12.ogg'>
<audio id='82' style='display:none;' src='sounds/DA12.ogg'>
<audio id='84' style='display:none;' src='sounds/NI12.ogg'>
<audio id='89' style='display:none;' src='sounds/RI22.ogg'>
<audio id='85' style='display:none;' src='sounds/GA22.ogg'>
<audio id='73' style='display:none;' src='sounds/MA22.ogg'>
<audio id='79' style='display:none;' src='sounds/DA22.ogg'>
<audio id='80' style='display:none;' src='sounds/NI12.ogg'>



<!-- TODO make it like this
<audio id='65' style='display:none;' src='sounds/hit.wav'
oncanplay="canplay()"
oncanplaythrough="another()"
onloadeddata="onloadeddata()">
-->
