<audio id='65' style='display:none;' src='sounds/a5.ogg'>
<audio id='83' style='display:none;' src='sounds/b5.ogg'>
<audio id='68' style='display:none;' src='sounds/c5.ogg'>
<audio id='70' style='display:none;' src='sounds/d5.ogg'>
<audio id='71' style='display:none;' src='sounds/e5.ogg'>
<audio id='72' style='display:none;' src='sounds/f5.ogg'>
<audio id='74' style='display:none;' src='sounds/g5.ogg'>
<audio id='75' style='display:none;' src='sounds/d5.ogg'>
<audio id='76' style='display:none;' src='sounds/a5.ogg'>
<audio id='59' style='display:none;' src='sounds/b5.ogg'>
<audio id='39' style='display:none;' src='sounds/c5.ogg'>
<!-- TODO make it like this
<audio id='65' style='display:none;' src='sounds/hit.wav'
oncanplay="canplay()"
oncanplaythrough="another()"
onloadeddata="onloadeddata()">
-->
